### ISSUE TITLE
Create page for entering new vending machine information

### ISSUE THREAD

**Issue by SarthakSirotiya** [SarthakSirotiya/UTVend#6]
Allow user to enter information about a new vending machine
- coordinates (based on device gps location)
- photo (camera intent?)
- description of the location (eg. "3rd floor, next to the elevator")
- additional notes (eg. "always out of doritos")

**Comment by CurveKiller** [comment]
Completed!
Gps is functioning
Instead of a camera intent we let the user pick an image from their device
Description of location is functioning
Additional notes is functioning

**Note** This uploads the image to cloud storage with the name of that path in the database
